// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGh2O-xUtCvJvVtNBsFkoDpLDEcYOlUM',
    appId: '1:475339212315:web:6dd31e1a297bf2550bdabe',
    messagingSenderId: '475339212315',
    projectId: 'shah-portfolio-2d2af',
    authDomain: 'shah-portfolio-2d2af.firebaseapp.com',
    databaseURL: 'https://shah-portfolio-2d2af-default-rtdb.firebaseio.com',
    storageBucket: 'shah-portfolio-2d2af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeUEE89HOKrT8490Q98WGdkbD_nNOuHIk',
    appId: '1:475339212315:android:c31426632fcd65260bdabe',
    messagingSenderId: '475339212315',
    projectId: 'shah-portfolio-2d2af',
    databaseURL: 'https://shah-portfolio-2d2af-default-rtdb.firebaseio.com',
    storageBucket: 'shah-portfolio-2d2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm6w3SNb2--oMI2euNmW536yDb6RafFbs',
    appId: '1:475339212315:ios:7499e2a879a920450bdabe',
    messagingSenderId: '475339212315',
    projectId: 'shah-portfolio-2d2af',
    databaseURL: 'https://shah-portfolio-2d2af-default-rtdb.firebaseio.com',
    storageBucket: 'shah-portfolio-2d2af.firebasestorage.app',
    iosBundleId: 'com.example.shahPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm6w3SNb2--oMI2euNmW536yDb6RafFbs',
    appId: '1:475339212315:ios:7499e2a879a920450bdabe',
    messagingSenderId: '475339212315',
    projectId: 'shah-portfolio-2d2af',
    databaseURL: 'https://shah-portfolio-2d2af-default-rtdb.firebaseio.com',
    storageBucket: 'shah-portfolio-2d2af.firebasestorage.app',
    iosBundleId: 'com.example.shahPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGh2O-xUtCvJvVtNBsFkoDpLDEcYOlUM',
    appId: '1:475339212315:web:166b49734e87664c0bdabe',
    messagingSenderId: '475339212315',
    projectId: 'shah-portfolio-2d2af',
    authDomain: 'shah-portfolio-2d2af.firebaseapp.com',
    databaseURL: 'https://shah-portfolio-2d2af-default-rtdb.firebaseio.com',
    storageBucket: 'shah-portfolio-2d2af.firebasestorage.app',
  );
}
